### ISSUE TITLE
Can no longer open this app as of today, it is giving an error message...

### ISSUE THREAD

**Issue by osmgit** [billthefarmer/currency#35]
This app was working perfect for a couple of weeks since i installed it, now when I go to open it just says "Unfortunately, Currency has stopped." 

I tried restarting the phone but it gave the same error message when opening.

I'm using a custom ROM with Android 6.0.1.

I've just done an uninstall and a reinstall and now it is working again.

**Comment by billthefarmer** [comment]
Most likely due to the stored settings getting corrupted somehow. Can't tell without a traceback.

**Comment by osmgit** [comment]
Ah yes I will see how it goes for now. If it happens again I will try deleting the stored data for the app. Not sure how to send a traceback sorry...

**Comment by exomar** [comment]
Also seeing this behaviour. This is error I see hope it helps:
```
FATAL EXCEPTION: main
Process: org.billthefarmer.currency, PID: 8944
java.lang.RuntimeException: Unable to resume activity {org.billthefarmer.currency/org.billthefarmer.currency.Main}: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.String
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3582)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3622)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2863)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1590)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6499)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:442)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.String
	at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:256)
	at org.billthefarmer.currency.Main.onResume(Main.java:341)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
	at android.app.Activity.performResume(Activity.java:7162)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3557)
	... 10 more
```

**Comment by billthefarmer** [comment]
OK, I found it. Also the app stopped working a few days ago due to the ECB moving to HTTPS. I will release a new version.

**Comment by billthefarmer** [comment]
See https://github.com/billthefarmer/currency/issues/37#issuecomment-419843392
