### ISSUE TITLE
Reference alternative FOSS apps for other currencies in README

### ISSUE THREAD

**Issue by alexanderadam** [billthefarmer/currency#38]
First of all: thank you for Currency. I love it and appreciate your work!

But as many other users before me (#1, #15, #17 or [this thread on F-Droid](https://forum.f-droid.org/t/currency-converter-that-includes-more-currencies/3512)) it also happened to me that there are currencies missing that I will need for vacation. And maybe (hopefully) [another attempt to add more currencies](https://github.com/billthefarmer/currency/issues/17#issuecomment-333571346) will work in the future.

But until then it would be nice to have some references to other FOSS apps in the README. It might help traveling people.
Maybe mentioning something like [Equate](https://f-droid.org/en/packages/com.llamacorp.equate/) which [seems to have different sources](https://github.com/EvanRespaut/Equate/blob/fd4dd6a58698cf07e440ad0a21af1162dc6eb648/app/src/main/java/com/llamacorp/equate/unit/updater/YahooXmlParser.java) (but it's interface hurts my eyes).

I hope you have a wonderful day!

**Comment by billthefarmer** [comment]
Well I looked at this, the app seems to work fine, but I don't think their data comes from Yahoo because AFAIK, that API was discontinued some time ago. Traceback in the device log from the app:
```shell
09-23 10:10:24.110  7877  7896 W System.err: java.io.FileNotFoundException: https://finance.yahoo.com/webservice/v1/symbols/allcurrencies/quote
09-23 10:10:24.121  7877  7896 W System.err:    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:250)
09-23 10:10:24.121  7877  7896 W System.err:    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
09-23 10:10:24.121  7877  7896 W System.err:    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
09-23 10:10:24.121  7877  7896 W System.err:    at com.llamacorp.equate.unit.updater.CurrencyURLParser.downloadAndParse(CurrencyURLParser.java:1068)
09-23 10:10:24.122  7877  7896 W System.err:    at com.llamacorp.equate.unit.updater.UnitUpdater$UpdateCurrenciesAsyncTask.updateRates(UnitUpdater.java:230)
09-23 10:10:24.122  7877  7896 W System.err:    at com.llamacorp.equate.unit.updater.UnitUpdater$UpdateCurrenciesAsyncTask.doInBackground(UnitUpdater.java:14104)
09-23 10:10:24.122  7877  7896 W System.err:    at android.os.AsyncTask$2.call(AsyncTask.java:305)
09-23 10:10:24.122  7877  7896 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-23 10:10:24.122  7877  7896 W System.err:    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
09-23 10:10:24.122  7877  7896 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-23 10:10:24.122  7877  7896 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-23 10:10:24.122  7877  7896 W System.err:    at java.lang.Thread.run(Thread.java:761)
```
Use curl to see what you get from that url:
```shell
$ curl https://finance.yahoo.com/webservice/v1/symbols/allcurrencies/quote
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   666  100   666    0     0   1332      0 --:--:-- --:--:-- --:--:--  1332
```
curl output, tidied up a bit:
```html
<html>
  <meta charset='utf-8'>
  <script>
    var u='https://www.yahoo.com/?err=404&err_url=https%3a%2f%2ffinance.yahoo.com%2fwebservice%2fv1%2fsymbols%2fallcurrencies%2fquote';
    if(window!=window.top){
      document.write('<p>Content is currently unavailable.</p><img src="//geo.yahoo.com/p?s=1197757039&t='+new Date().getTime()+'&_R='+encodeURIComponent(document.referrer)+'&err=404&err_url='+u+'" width="0px" height="0px"/>');
    }else{
      window.location.replace(u);
    }
  </script>
  <noscript>
    <META http-equiv="refresh" content="0;URL='https://www.yahoo.com/?err=404&err_url=https%3a%2f%2ffinance.yahoo.com%2fwebservice%2fv1%2fsymbols%2fallcurrencies%2fquote'">
  </noscript>
</html>
```
Coinmarketcap to get cryptocurrencies, which works. Don't know what the rules are, though: https://coinmarketcap.com/api. There's a reference in the code to `http://rate-exchange.herokuapp.com/fetchRate?from= + DEFAULT_CURRENCY + &to=`, but commented out.

**Comment by billthefarmer** [comment]
Well I worked out what's happened with Equate which explains why it appears to work with currencies not from the ECB. The currencies are initialised in code [here](https://github.com/EvanRespaut/Equate/blob/master/app/src/main/java/com/llamacorp/equate/unit/UnitInitializer.java), but in [this commit](https://github.com/EvanRespaut/Equate/commit/1d77ddc80a92812465582f5d4e46f7f65f3f0d9a) all the ones probably from from Yahoo have been commented out. I've got version 1.6 from F-Droid which doesn't include the fix in this commit.

**Comment by alexanderadam** [comment]
Wow, Bill you are indeed a fast responding maintainer. :wink: 

This issue was _not_ about connecting those API's, however. It was about adding a reference to the README.

But **if** you want to implement Yahoo Finance (we should move the technical aspects rather to #17!?):

It still seems to be possible to request currency data as JSON.

```bash
$ curl 'https://query1.finance.yahoo.com/v7/finance/spark?symbols=EURUSD=X&range=1d&interval=5m&indicators=close&includeTimestamps=true&includePrePost=true&corsDomain=finance.yahoo.com&.tsrc=finance'
```
The conversion rate seems to be in the key `chartPreviousClose`. You even 
The `symbols` parameter contains the ISO codes for the currencies someone want to know. So let's say you want to know the relation of the Peruvian Sol you have to use it's [ISO code `PEN`](https://en.wikipedia.org/wiki/Peruvian_sol). The request is therefore

```bash
$ curl 'https://query1.finance.yahoo.com/v7/finance/spark?symbols=EURPEN=X&range=1d&interval=5m&indicators=close&includeTimestamps=true&includePrePost=true&corsDomain=finance.yahoo.com&.tsrc=finance'
```

You probably can set `includeTimestamps` and `includePrePost` to false to lower the amount of data that have to be requested.

Thank you again for responding so fast!

**Comment by billthefarmer** [comment]
Ah well, you asked me to add a link to Equate, which I hadn't seen. When I wrote this app I could only find an old abandoned app on F-Droid, which this is partially forked from. There are plenty on Google, including a couple of copies of this one with added ads. I put the link in and then checked out Equate and found that the Yahoo part had stopped working, which the developer appears to have fixed by commenting it out. So the latest version possibly only has the same currencies as this.

**Comment by billthefarmer** [comment]
That's because it's initial value is set in code which has since been commented out in version 1.7 from the app store, or when it gets to F-Droid. See links above and https://github.com/EvanRespaut/Equate/blob/master/app/src/main/java/com/llamacorp/equate/unit/UnitInitializer.java#L485.
